#!/bin/sh
set -e

export NGINX_WEB_INDEX_FILE_DOT_ESCAPED=${NGINX_WEB_INDEX_FILE//./\\.}
export DOLLAR="$"
envsubst < /etc/nginx/conf.d/${NGINX_PROJECT_TYPE}.conf.tpl > /etc/nginx/conf.d/default.conf

exec "$@"