services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=symfony-flex APP_CACHE_DIR=var\\/cache APP_LOGS_DIR=var\\/logs APP_SESSIONS_DIR=var\\/sessions
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=symfony-2 APP_CACHE_DIR=app\\/cache APP_LOGS_DIR=app\\/logs APP_SESSIONS_DIR=app\\/sessions APP_PHP_VERSION=5.6

before_install:
  - sudo service mysql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - cp .env.dist .env
  - sed -i "s/PROJECT_TYPE=symfony-flex/PROJECT_TYPE=$PROJECT_TYPE/" .env
  - sed -i "s/APP_CACHE_DIR=var\/cache/APP_CACHE_DIR=$APP_CACHE_DIR/" .env
  - sed -i "s/APP_LOGS_DIR=var\/logs/APP_LOGS_DIR=$APP_LOGS_DIR/" .env
  - sed -i "s/APP_SESSIONS_DIR=var\/sessions/APP_SESSIONS_DIR=$APP_SESSIONS_DIR/" .env
  - echo -ne "source \"https://rubygems.org\"\ngem \"capistrano\"\ngem \"capistrano-composer\"\n" > Gemfile

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec app php -v
  - docker-compose -f ./docker-compose.capistrano.yaml build
  - docker-compose -f ./docker-compose.capistrano.yaml up -d
  - docker-compose -f ./docker-compose.capistrano.yaml exec capistrano cap -V
  - docker-compose -f ./docker-compose.capistrano.yaml run capistrano cap -V
  - docker ps -a