services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=symfony-flex
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=symfony-flex APP_PHP_VERSION=7.2
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=symfony-2    APP_PHP_VERSION=5.6 NGINX_WEB_INDEX_FILE=app_dev.php
  - DOCKER_COMPOSE_VERSION=1.20.1 PROJECT_TYPE=wordpress    APP_PHP_VERSION=5.6

before_install:
  - sudo service mysql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - cp .env.dist .env
  - sed -i "s/PROJECT_TYPE=.*/PROJECT_TYPE=$PROJECT_TYPE/g" .env
  - sed -i "s/APP_PHP_VERSION=.*/APP_PHP_VERSION=$APP_PHP_VERSION/g" .env
  - sed -i "s/NGINX_WEB_INDEX_FILE=.*/NGINX_WEB_INDEX_FILE=$NGINX_WEB_INDEX_FILE/g" .env

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec app php -v
  - docker-compose -f ./docker-compose.capistrano.yaml build
  - docker-compose -f ./docker-compose.capistrano.yaml up -d
  - docker-compose -f ./docker-compose.capistrano.yaml exec capistrano cap -V
  - docker-compose -f ./docker-compose.capistrano.yaml run capistrano cap -V
  - docker-compose logs
  - docker ps -a