version: '3'

services:
  app:
    build:
      context: ${DOCKER_APP_CONFIG_DIR}
      args:
        PHP_VERSION: ${APP_PHP_VERSION}
        APP_ROOT: ${APP_ROOT}
    depends_on:
      - db
      - mailhog
    volumes:
      #PHP config files
      - ${DOCKER_APP_CONFIG_DIR}/php:/usr/local/etc/php/conf.custom.d/
      #SRC folder of your project
      - ${PROJECT_DIR}:${APP_ROOT}
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - ${APP_ROOT}/var/
      - ${APP_ROOT}/var/cache/
      - ${APP_ROOT}/var/logs/
      - ${APP_ROOT}/var/sessions/
    ports:
      - '${PHP_PORT}:9000'

  nginx:
    build:
      context: ${DOCKER_NGINX_CONFIG_DIR}
      args:
        NGINX_ROOT: ${APP_ROOT}
    environment:
        NGINX_WEB_FOLDER: ${NGINX_WEB_FOLDER:-"public"}
        NGINX_WEB_INDEX_FILE: ${NGINX_WEB_INDEX_FILE:-"index.php"}
    depends_on:
      - app
    volumes:
      - ${PROJECT_DIR}:${APP_ROOT}:ro
    ports:
      - '${NGINX_PORT}:80'
      - '${NGINX_S_PORT}:443'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - /var/lib/mysql
     - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
     - '${MYSQL_PORT}:3306'
   
  mailhog:
    image: mailhog/mailhog
    ports:
       - "${MAILHOG_PORT1}:1025"
       - "${MAILHOG_PORT2}:8025"
