version: "3.6"

services:
  app:
    build:
      context: ${DOCKER_APP_CONFIG_DIR:-./config/app}
      args:
        PHP_VERSION: ${APP_PHP_VERSION}
        APP_ROOT: ${APP_ROOT}
        APP_PHP_EXTRA_EXTENSIONS: ${APP_PHP_EXTRA_EXTENSIONS}
    environment:
        XDEBUG_CONFIG: ${APP_PHP_XDEBUG_CONFIG:-idekey=myide}
        TIMEZONE: ${APP_PHP_TIMEZONE:-UTC}
        APP_PROJECT_TYPE: ${PROJECT_TYPE}
        COMPOSER_MEMORY_LIMIT: ${APP_PHP_COMPOSER_MEMORY_LIMIT:--1}
        COMPOSER_PROCESS_TIMEOUT: ${APP_PHP_COMPOSER_PROCESS_TIMEOUT:-600}
    depends_on:
      - db
      - mailhog
    volumes:
      # PHP config files
      - ${DOCKER_APP_PHP_EXTRA_CONFIG_DIR:-./config/app/php/conf.custom.d}:/usr/local/etc/php/conf.custom.d/
      - ${PROJECT_DIR}:${APP_ROOT}:cached
    entrypoint:
      - app-entrypoint.sh
      - docker-php-entrypoint
    command:
      - php-fpm

  nginx:
    build:
      context: ${DOCKER_NGINX_CONFIG_DIR:-./config/nginx}
      args:
        NGINX_ROOT: ${APP_ROOT}
    environment:
        NGINX_PROJECT_TYPE: ${PROJECT_TYPE}
        NGINX_WEB_FOLDER: ${NGINX_WEB_FOLDER}
        NGINX_WEB_INDEX_FILE: ${NGINX_WEB_INDEX_FILE}
    depends_on:
      - app
    volumes:
      - ${PROJECT_DIR}:${APP_ROOT}:ro
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_S_PORT}:443"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - /var/lib/mysql
     - ${MYSQL_DUMP_DIR}:/docker-entrypoint-initdb.d:ro
    ports:
     - "${MYSQL_PORT}:3306"
   
  mailhog:
    image: mailhog/mailhog
    ports:
       - "${MAILHOG_PORT1}:8025"
       - "${MAILHOG_PORT2}:1025"
