version: '3'

services:
  app:
    extends:
        file: ${PROJECT_TYPE}.yaml
        service: app
    build:
      context: ${DOCKER_APP_CONFIG_DIR}
      args:
        PHP_VERSION: ${APP_PHP_VERSION}
        APP_ROOT: ${APP_ROOT}
        APP_PROJECT_TYPE: ${PROJECT_TYPE}
    depends_on:
      - db
      - mailhog
    volumes:
      # PHP config files
      - ${DOCKER_APP_CONFIG_DIR}/php/conf.custom.d:/usr/local/etc/php/conf.custom.d/
      #SRC folder of your project
      - ${PROJECT_DIR}:${APP_ROOT}
    entrypoint:
      - script-${PROJECT_TYPE}.sh
      - docker-php-entrypoint
    command:
      - php-fpm
    ports:
      - '${PHP_PORT}:9000'

  nginx:
    build:
      context: ${DOCKER_NGINX_CONFIG_DIR}
      args:
        NGINX_ROOT: ${APP_ROOT}
        NGINX_PROJECT_TYPE: ${PROJECT_TYPE}
    environment:
        NGINX_WEB_FOLDER: ${NGINX_WEB_FOLDER:-"public"}
        NGINX_WEB_INDEX_FILE: ${NGINX_WEB_INDEX_FILE:-"index.php"}
    depends_on:
      - app
    volumes:
      - ${PROJECT_DIR}:${APP_ROOT}:ro
    ports:
      - '${NGINX_PORT}:80'
      - '${NGINX_S_PORT}:443'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
     - /var/lib/mysql
     - ${MYSQL_DUMP_FILE}:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
     - '${MYSQL_PORT}:3306'
   
  mailhog:
    image: mailhog/mailhog
    ports:
       - "${MAILHOG_PORT1}:1025"
       - "${MAILHOG_PORT2}:8025"
