version: '3.6'

services:
  capistrano:
    build:
      context: ${DOCKER_CAPISTRANO_CONFIG_DIR:-./config/capistrano}
      args:
        CAPISTRANO_ROOT: ${APP_ROOT:-/var/www/html}
    volumes:
      - ${PROJECT_DIR}:${APP_ROOT}:cached
      - ${CAPISTRANO_SSH_USER_DIR}:/root/.ssh
