version: '3'

services:
  app:
    build:
    volumes:
      # BEGIN symfony-flex
      - ${APP_ROOT}/var/
      - ${APP_ROOT}/var/cache/
      - ${APP_ROOT}/var/logs/
      - ${APP_ROOT}/var/sessions/
      # END symfony-flex
    entrypoint:
      -
