#!/bin/sh

set -e

if [ ! -x "/usr/local/bundle/bin/cap" ]
then
	echo "First install of capistrano ..."
    gem install capistrano
fi

if [[ -f "./Gemfile" &&  ]]
then
	echo "Gemfile detected, installing needed gem ..."
    bundle install
fi

exec "$@"
